name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        working-directory: ./web

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: |
        ls
        npm install
    
    - name: 'Run Tests'
      run: npm run test  

    - name: 'Run coverage'
      run: npm run coverage
