name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'
      with: 
        path: web

    - name: 'Install Dependencies'
      working-directory: web/    
      run: |
        ls
        npm install
    
    - name: 'Run Tests'
      working-directory: web/    
      run: npm run test